#include <iostream>
#include <list>
#include <vector>

namespace Game
{
    std::vector<std::list<std::string>> islandMaps = {
        {
            "    oo",
            "  ooooo",
            "oooooooo",
            " oooooooooo",
            " oooooooooo",
            "  ooooooooo",
            "  oooooooooooo",
            " oooooooooooooo",
            " oooooooooooooo",
            "  ooooooooooooo",
            "  oooooooooooo",
            "    oooooooooo",
            "   ooooooooo",
            "    ooooooo",
        },
        {
            "oooooooooooooooooooooooooooooo",
            " oooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooo",
            "   oooooooooooooooooooooooooooooo",
            "      oooooooooooooooooooooooooooooo",
            "        oooooooooooooooooooooooooooooo",
            "          oooooooooooooooooooooooooooooo",
            "            oooooooooooooooooooooooooooooo",
            "              oooooooooooooooooooooooooooooo",
            "                 oooooooooooooooooooooooooooooo",
            "                   oooooooooooooooooooooooooooooo",
            "                     oooooooooooooooooooooooooooooo",
            "                        oooooooooooooooooooooooooooooo",
            "                          oooooooooooooooooooooooooooooo",
            "                             oooooooooooooooooooooooooooooo",
            "                                oooooooooooooooooooooooooooooo",
            "                                   oooooooooooooooooooooooooooooo",
            "                                     oooooooooooooooooooooooooooooo",
            "                                      oooooooooooooooooooooooooooooo",
            "                                        oooooooooooooooooooooooooooooo",
            "                                          oooooooooooooooooooooooooooooo",
            "                                             oooooooooooooooooooooooooooooo",
            "                                             oooooooooooooooooooooooooooooo",
            "                                              oooooooooooooooooooooooooooooo",
            "                                                oooooooooooooooooooooooooooooo",
            "                                                  oooooooooooooooooooooooooooooo",
            "                                                    oooooooooooooooooooooooooooooo",
            "                                                    oooooooooooooooooooooooooooooo",
            "                                                    oooooooooooooooooooooooooooooo",
            "                                                    oooooooooooooooooooooooooooooo",
            "                                                     oooooooooooooooooooooooooooooo",
            "                                                       oooooooooooooooooooooooooooooo",
            "                                                         oooooooooooooooooooooooooooooo",
            "                                                           oooooooooooooooooooooooooooooo",
            "                                                              oooooooooooooooooooooooooooooo",
            "                                                                oooooooooooooooooooooooooooooo",
            "                                                                  oooooooooooooooooooooooooooooo",
            "                                                                   oooooooooooooooooooooooooooooo",
            "                                                                     oooooooooooooooooooooooooooooo",
            "                                                                       oooooooooooooooooooooooooooooo",
            "                                                                         oooooooooooooooooooooooooooooo",
            "                                                                          oooooooooooooooooooooooooooooo",
            "                                                                            oooooooooooooooooooooooooooooo",
            "                                                                             oooooooooooooooooooooooooooooo",
            "                                                                               oooooooooooooooooooooooooooooo",
            "                                                                                 oooooooooooooooooooooooooooooo",
            "                                                                                   oooooooooooooooooooooooooooooo",
            "                                                                                      oooooooooooooooooooooooooooooo",
            "                                                                                      oooooooooooooooooooooooooooooo",
            "                                                                                      oooooooooooooooooooooooooooooo",
            "                                                                                      oooooooooooooooooooooooooooooo",
            "                                                                                         oooooooooooooooooooooooooooooo",
            "                                                                                           oooooooooooooooooooooooooooooo",
            "                                                                                             oooooooooooooooooooooooooooooo",
            "                                                                                               oooooooooooooooooooooooooooooo",
            "                                                                                                oooooooooooooooooooooooooooooo",
            "                                                                                                 oooooooooooooooooooooooooooooo",
            "                                                                                                   oooooooooooooooooooooooooooooo",
            "                                                                                                     oooooooooooooooooooooooooooooo",
            "                                                                                                      oooooooooooooooooooooooooooooo",
            "                                                                                                      oooooooooooooooooooooooooooooo",
            "                                                                                                      oooooooooooooooooooooooooooooo",
            "                                                                                                      oooooooooooooooooooooooooooooo",
            "                                                                                                      oooooooooooooooooooooooooooooo",
            "                                                                                                        oooooooooooooooooooooooooooooo",
            "                                                                                                          oooooooooooooooooooooooooooooo",
            "                                                                                                            oooooooooooooooooooooooooooooo",
            "                                                                                                              oooooooooooooooooooooooooooooo",
            "                                                                                                                oooooooooooooooooooooooooooooo",
            "                                                                                                                 oooooooooooooooooooooooooooooo",
            "                                                                                                                   oooooooooooooooooooooooooooooo",
            "                                                                                                                     oooooooooooooooooooooooooooooo",
            "                                                                                                                       oooooooooooooooooooooooooooooo",
            "                                                                                                                     oooooooooooooooooooooooooooooo",
            "                                                                                                                  oooooooooooooooooooooooooooooo",
            "                                                                                                                oooooooooooooooooooooooooooooo",
            "                                                                                                              oooooooooooooooooooooooooooooo",
        },
        {
            "           ooooooooo",
            "        oooooooooooooo",
            "    ooooooooooooooooooooo",
            "  ooooooooooooooooooooooooooo",
            "oooooooo       ooooooooooooooooo",
            "ooooooooooo    ooooooooooooooooooo",
            "ooooooooooo    ooooooooooooooooooo",
            " oooooooooo       ooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooo",
            " ooooooooooooooooooooooooooooooooooooo",
            " oooooooooooooooooooooooooooooooooooooo",
            "  ooooooooooooooooooooooooooooooooooo",
            "   ooooooooooooooooooooooooooooooooo",
            "    oooooooooooooooooooooooooooooo",
            "   ooooooooo    ooooooooooooooooo",
            "    ooooooo      ooooooooooooooo",
            "     oooooo      oooooooooooooooo",
            "     oooooo      oooooooooooooooo",
            "    oooooo       oooooooooooooooooo",
            "   ooooooooooooooooooooooooooooooooo",
            "   oooooooooooooooooooooooooooooooo",
            "   oooooooooooooooooooooooooooooooo",
            "     oooooooooooooooooooooooooooooooo",
            "       oooooooooooooooooooooooooooooooo",
            "        oooooooooooooooooooooooooooooooooooo",
            "            ooooooooooooooooooooooooooooooooooooooo",
            "              oooooooooooooooooooooooooooooooooooooooooo",
            "               oooooooooooooooooooooooooooooooooooooooooo",
            "                   ooooooooooooooooooooooooooooooooooooooo",
            "                     oooooooooooooooooooooooooooooooooooo",
            "                     ooooooooooooooooooooooooooooooooooo",
            "                     ooooooooooooooooooooooooooooooooooo",
            "                     ooooooooooooooooooooooooooooooooooo",
            "                    ooooooooooooooooooooooooooooooooooo",
            "                  ooooooooooooooooooooooooooooooooooo",
            "                ooooooooooooooooooooooooooooooooooo",
            "               ooooooooooooooooooooooooooooooo",
            "              ooooooooooooooooooooooooooooooo",
            "               ooooooooooooooooooooooooooooo",
            "                   oooooooooooooooooooooo",
        },
        {
            "              oooooooooo",
            "          oooooooooooooooo",
            "       ooooooooooooooooooo",
            "      ooooooooooooooooooooo",
            "     ooooooooooooooooooooo",
            "     oooooooooooooooooooo",
            "   ooooooooooooooooooooooo",
            "  ooooooooooooooooooooooooo",
            " ooooooooooooooooooooooooo",
            " oooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooo",
            " ooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooo",
            "  ooooooooooooooooooooooooooo",
            " ooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooo",
            " ooooooooooooooooooooooo",
            "   oooooooooooooo",
            "  oooooooooooo",
            "   ooooooo",
        },
        {
            "                                 ooooooooooo",
            "                             ooooooooooooooooooo",
            "                       oooooooooooooooooooooooooooooo",
            "                    oooooooooooooooooooooooooooooooooooooo",
            "                oooooooooooooooooooooooooooooooooooooooooo",
            "              oooooooooooooooooooooooooooooooooooooooooooooo",
            "            ooooooooooooooooooooooooooooooooooooooooooooooo",
            "        oooooooooooooooooooooooooooooooooooooooooooooooooo",
            "        oooooooooooooooooooooooooooooooooooooooooooooooooo",
            "        ooooooooooooooooooooooooooooooooooooooooooooooo",
            "      ooooooooooooooooooooooooooooooooooooooooooo",
            "       ooooooooooooooooooooooooooooooooo",
            "        oooooooooooooooooooooooooooooo",
            "       ooooooooo      ooooooooooooooo",
            "        ooooooo        ooooooooooooo",
            "         oooooo         ooooooooooooo",
            "        ooooooo         oooooooooooooo",
            "    ooooooooooo       ooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooooooooooo",
            " ooooooooooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooo",
            " oooooooooooooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooooooooooooooooooooo",
            "  ooooooooooooooooooooooooooooooooooooooooooooo",
            "     oooooooooooooooooooooooooooooooooooooooooo",
            "       ooooooooooooooooooooooooooooooooooooooo",
            "          ooooooooooooooooooooooooooooooooooo",
            "           ooooooooooooooooooooooooooooooooo",
            "            oooooooooooooooooooooooooooooooo",
            "              ooooooooooooooooooooooooooooo",
            "                 oooooooooooooooooooooooo",
            "                    oooooooooooooooooo",
            "                        oooooooooooo",
            "                          ooooooo",
        },
        {
            "                                                     ooooooooooo",
            "                                                 ooooooooooooooooooo",
            "                                           oooooooooooooooooooooooooooooo",
            "                                        oooooooooooooooooooooooooooooooooooooo",
            "                                    ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                                  oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                                oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                   oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "              ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "         oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "    ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooo                                    ooooooooooooooooooooooooooooooooooooooooooooooooooo",
            " ooooooooooooooooooooooooooooooooooo                                        ooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooooo                                              oooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooooo                                                 ooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooo                                                   ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            " oooooooooooooooooooooooooooo                                                     ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooo                                                        oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "   ooooooooooooooooooooooooo                                                        oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "   ooooooooooooooooooooooooooo                                                     oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "   oooooooooooooooooooooooooooo                                                  ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "    ooooooooooooooooooooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "      oooooooooooooooooooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "       ooooooooooooooooooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "         ooooooooooooooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "            oooooooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "               ooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                 oooooooo                                                     ooooooooooooooooooooooooooooooooooooooooooooooo",
            "                                                                                 ooooooooooooooooooooooooooooooooooooooooo",
            "                                                                                   ooooooooooooooooooooooooooooooooo",
            "                                                                                     ooooooooooooooooooooooooooo",
        },
        {
            "           ooooooooooooooo",
            "         ooooooooooooooooooo",
            "      ooooooooooooooooooooooo",
            "    oooooooooooooooooooooooooo",
            "   ooooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooooooo",
            "   ooooooooooooooooooooooooooooooooooooooooo",
            "    ooooooooooooooooooooooooooooooooooooooooooo",
            "     oooooooooooooooooooooooooooooooooooooooooo",
            "     ooooooooooooooooooooooooooooooooooooooooo",
            "     oooooooooooooooooooooooooooooooooooooo",
            "      ooooooooooooooooooooooooooooooooo",
            "        oooooooooooooooooooooooooooooooo",
            "         ooooooooooooooooooooooooooooooo",
            "           ooooooooooooooooooooooooooo",
            "             ooooooooooooooooooooooooo",
            "             ooooooooooooooooooooooooo",
            "              oooooooooooooooooooooooo",
            "               oooooooooooooooooooooo",
            "                oooooooooooooooooooo",
            "                   oooooooooooooooo",
            "                      ooooooooooo",
            "                      ooooooooooo",
            "                      ooooooooooo",
            "                      ooooooooooo",
            "                  ooooooooooooooooooo",
            "            oooooooooooooooooooooooooooooo",
            "         oooooooooooooooooooooooooooooooooooooo",
            "     ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "   oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            " oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            " ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "   ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "      ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                                         oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                                            ooooooooooooooooooooooooooooooooooooooooooooooo",
            "                                                  ooooooooooooooooooooooooooooooooooooooooo",
            "                                                    ooooooooooooooooooooooooooooooooo",
            "                                                      ooooooooooooooooooooooooooo",
            "                                                     oooooooooooooooooooooooooo",
            "                                                    ooooooooooooooooooooooooooooooo",
            "                                                   oooooooooooooooooooooooooooooooooooo",
            "                                                   oooooooooooooooooooooooooooooooooooooo",
            "                                                   oooooooooooooooooooooooooooooooooooooooo",
            "                                                    ooooooooooooooooooooooooooooooooooooooooo",
            "                                                     ooooooooooooooooooooooooooooooooooooooooooo",
            "                                                      oooooooooooooooooooooooooooooooooooooooooooo",
            "                                                      ooooooooooooooooooooooooooooooooooooooooo",
            "                                                      oooooooooooooooooooooooooooooooooooooo",
            "                                                       ooooooooooooooooooooooooooooooooo",
            "                                                         oooooooooooooooooooooooooooooooo",
            "                                                          ooooooooooooooooooooooooooooooo",
            "                                                            ooooooooooooooooooooooooooo",
            "                                                                    oooooooooooooooooo",
            "                                                                       ooooooooooo",
        },
        {
            "              oooooooooo",
            "          oooooooooooooooo",
            "       ooooooooooooooooooo",
            "      ooooooooooooooooooooo",
            "     ooooooooooooooooooooo",
            "     oooooooooooooooooooo",
            "   ooooooooooooooooooooooo",
            "  ooooooooooooooooooooooooo",
            " oooooooo             ooooooooooooooooo",
            " oooooooo             oooooooooooooooooooo",
            "ooooooooo             ooooooooooooooooooooooooo",
            " oooooooo             ooooooooooooooooooooooooooo",
            "  ooooooo             oooooooooooooooooooooooooooo",
            "  ooooooo             oooooooooooooooooooooooooo",
            "  ooooooo             oooooooooooooooooooooooo",
            " oooooooo             ooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooo",
            " ooooooooooooooooooooooo",
            "   oooooooooooooooooo",
            "       oooooooooooo",
            "           ooooooo",
        }};

} // namespace Game
