#include <iostream>
#include <list>
#include <vector>

namespace Game
{
    std::vector<std::list<std::string>> islandMaps = {
        {
            "    oo",
            "  ooooo",
            "oooooooo",
            " oooooooooo",
            " oooooooooo",
            "  ooooooooo",
            "  oooooooooooo",
            " oooooooooooooo",
            " oooooooooooooo",
            "  ooooooooooooo",
            "  oooooooooooo",
            "    oooooooooo",
            "   ooooooooo",
            "    ooooooo",
        },
        {
            "           ooooooooo",
            "        oooooooooooooo",
            "    ooooooooooooooooooooo",
            "  ooooooooooooooooooooooooooo",
            "oooooooo    oooooooooooooooooooo",
            " oooooooooo    ooooooooooooooooooo",
            " oooooooooo    ooooooooooooooooooo",
            "  ooooooooo       ooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooo",
            " ooooooooooooooooooooooooooooooooooooo",
            " oooooooooooooooooooooooooooooooooooooo",
            "  ooooooooooooooooooooooooooooooooooo",
            "   ooooooooooooooooooooooooooooooooo",
            "    oooooooooooooooooooooooooooooo",
            "   ooooooooo   oooooooooooooooooo",
            "    ooooooo    ooooooooooooooooo",
            "     oooooo    oooooooooooooooooo",
            "     oooooo    ooooooooooooooooooo",
            "     ooooo      oooooooooooooooooooo",
            "   oooooooooooooooooooooooooooooooooo",
            "   oooooooooooooooooooooooooooooooo",
            "   oooooooooooooooooooooooooooooooo",
            "     oooooooooooooooooooooooooooooooo",
            "       oooooooooooooooooooooooooooooooo",
            "        oooooooooooooooooooooooooooooooooooo",
            "            ooooooooooooooooooooooooooooooooooooooo",
            "              oooooooooooooooooooooooooooooooooooooooooo",
            "               oooooooooooooooooooooooooooooooooooooooooo",
            "                   ooooooooooooooooooooooooooooooooooooooo",
            "                     oooooooooooooooooooooooooooooooooooo",
            "                     ooooooooooooooooooooooooooooooooooo",
        },
        {
            "                                 ooooooooooo",
            "                             ooooooooooooooooooo",
            "                       oooooooooooooooooooooooooooooo",
            "                    oooooooooooooooooooooooooooooooooooooo",
            "                oooooooooooooooooooooooooooooooooooooooooo",
            "              oooooooooooooooooooooooooooooooooooooooooooooo",
            "            ooooooooooooooooooooooooooooooooooooooooooooooo",
            "        oooooooooooooooooooooooooooooooooooooooooooooooooo",
            "        oooooooooooooooooooooooooooooooooooooooooooooooooo",
            "        ooooooooooooooooooooooooooooooooooooooooooooooo",
            "      ooooooooooooooooooooooooooooooooooooooooooo",
            "       ooooooooooooooooooooooooooooooooo",
            "        oooooooooooooooooooooooooooooo",
            "       ooooooooo      ooooooooooooooo",
            "        ooooooo        ooooooooooooo",
            "         oooooo         ooooooooooooo",
            "        ooooooo         oooooooooooooo",
            "    ooooooooooo       ooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooooooooooo",
            " ooooooooooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooo",
            " oooooooooooooooooooooooooooooooooooooooo",
            "oooooooooooooooooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooooooooooooooooooooo",
            "  ooooooooooooooooooooooooooooooooooooooooooooo",
            "     oooooooooooooooooooooooooooooooooooooooooo",
            "       ooooooooooooooooooooooooooooooooooooooo",
            "          ooooooooooooooooooooooooooooooooooo",
            "           ooooooooooooooooooooooooooooooooo",
            "            oooooooooooooooooooooooooooooooo",
            "              ooooooooooooooooooooooooooooo",
            "                 oooooooooooooooooooooooo",
            "                    oooooooooooooooooo",
            "                        oooooooooooo",
            "                          ooooooo",
        },
        {
            "                                                     ooooooooooo",
            "                                                 ooooooooooooooooooo",
            "                                           oooooooooooooooooooooooooooooo",
            "                                        oooooooooooooooooooooooooooooooooooooo",
            "                                    ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                                  oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                                oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                   oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "              ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "         oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "    ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooooooooooooo                                    ooooooooooooooooooooooooooooooooooooooooooooooooooo",
            " ooooooooooooooooooooooooooooooooooo                                        ooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooooo                                              oooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooooo                                                 ooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "ooooooooooooooooooooooooooooo                                                   ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            " oooooooooooooooooooooooooooo                                                     ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "  oooooooooooooooooooooooooo                                                        oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "   ooooooooooooooooooooooooo                                                        oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "   ooooooooooooooooooooooooooo                                                     oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "   oooooooooooooooooooooooooooo                                                  ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "    ooooooooooooooooooooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "      oooooooooooooooooooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "       ooooooooooooooooooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "         ooooooooooooooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "            oooooooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "               ooooooooooo                                                 oooooooooooooooooooooooooooooooooooooooooooooooooooo",
            "                 oooooooo                                                     ooooooooooooooooooooooooooooooooooooooooooooooo",
            "                                                                                 ooooooooooooooooooooooooooooooooooooooooo",
            "                                                                                   ooooooooooooooooooooooooooooooooo",
            "                                                                                     ooooooooooooooooooooooooooo",
        }};

} // namespace Game
